### ISSUE TITLE
Declarations referenced in a dependent template argument may get removed

### ISSUE THREAD

**Issue by AlCash07** [slycelote/caide-cpp-inliner#8]
Example: [http://ideone.com/QaLeKP](http://ideone.com/QaLeKP)

If I rewrite the function in the following way, everything works:
`template <class Y>
void f(Y& y) {
typename Y::value_type value = 42;
y.value = value;
}`

**Comment by AlCash07** [comment]
This issue is actually very important for template metaprogramming. The following example fails on multiple levels: [https://ideone.com/8UCOkK](https://ideone.com/8UCOkK)

**Comment by jcg9129** [comment]
Any update on this?

**Comment by slycelote** [comment]
No, but I'll try to look into it and see if things changed with recent clang.
Do you have your own example? Things might be subtly different, so it's good to have as many test cases as possible.

**Comment by slycelote** [comment]
ok, at least simple cases should work now.
Let me know if there's some specific scenario that is still failing for you.

**Comment by jcg9129** [comment]
Hi, @slycelote. This case fails https://pastebin.com/ipEMpeLC.

**Comment by slycelote** [comment]
That's an unrelated problem; support for concepts is new and I expect you'll find more issues. I fixed this one.

**Comment by jcg9129** [comment]
Hi, @slycelote. Those three still fail: https://pastebin.com/W2yDdMFJ, https://pastebin.com/eFiqanZg and https://pastebin.com/ir6ACLAC. Only the last two use concepts.

**Comment by slycelote** [comment]
The first one (without `requires` clause) works for me. Can you confirm you're synced to the latest commit? Also, what clang version are you using?

**Comment by jcg9129** [comment]
> The first one (without `requires` clause) works for me. Can you confirm you're synced to the latest commit? Also, what clang version are you using?

You are right. I was building with an old version. The first code works for me now. I am using this Docker file to build the app https://pastebin.com/Mn3K8ERg.

**Comment by slycelote** [comment]
This should largely work now 🥵.
I'm going to close this generic issue, please open new ones for specific problems.
Also, this will require latest clang (19.1).
